name: Pushed

on:
  push:
    paths:
      - '**.luau'
      - '**.lua'
      - '**.rbxm'
      - '**.json'
      - '**.yml'
  pull_request:
    paths:
      - '**.luau'
      - '**.lua'
      - '**.rbxm'
      - '**.json'
      - '**.yml'

permissions:
  contents: write

jobs:
  build-script:
    name: Bundle and Upload Scoot Plus
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup RoKit
        uses: CompeyDev/setup-rokit@v0.1.2

      - name: Install Necessary Tools
        run: |
          rokit trust rojo-rbx/rojo
          rokit trust lune-org/lune
          rokit trust seaofvoices/darklua
          rokit trust UpliftGames/wally
          rokit trust JohnnyMorganz/wally-package-types
          rokit install

      - name: Build
        run: lune run build bundle output="Distribution/Scoot.luau" minify=true env-name="Scoot Plus" temp-dir-base="Distribution" extra-offset-lines=0 ci-mode=true verbose=true

      - name: Upload Minified Scoot Plus to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Scoot.luau
          path: Distribution/Scoot.luau
